// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/proto/errors/v1/errors.proto

package errorsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppErrorCode defines a list of standardized, application-specific error codes.
type AppErrorCode int32

const (
	AppErrorCode_APP_ERROR_CODE_UNSPECIFIED AppErrorCode = 0
	// Validation failures
	AppErrorCode_VALIDATION_FAILED  AppErrorCode = 1
	AppErrorCode_REQUIRED_FIELD     AppErrorCode = 2
	AppErrorCode_TOO_SHORT          AppErrorCode = 3
	AppErrorCode_TOO_LONG           AppErrorCode = 4
	AppErrorCode_INVALID_FORMAT     AppErrorCode = 5
	AppErrorCode_MUST_BE_FUTURE     AppErrorCode = 6
	AppErrorCode_INVALID_VALUE      AppErrorCode = 7
	AppErrorCode_DUPLICATE_TAG      AppErrorCode = 8
	AppErrorCode_INVALID_TAG_FORMAT AppErrorCode = 9
	AppErrorCode_OVERDUE_COMPLETION AppErrorCode = 10
	AppErrorCode_EMPTY_BATCH        AppErrorCode = 11
	AppErrorCode_BATCH_TOO_LARGE    AppErrorCode = 12
	AppErrorCode_DUPLICATE_TITLE    AppErrorCode = 13
	// Resource errors
	AppErrorCode_RESOURCE_NOT_FOUND AppErrorCode = 1001
	AppErrorCode_RESOURCE_CONFLICT  AppErrorCode = 1002
	// Authentication and authorization
	AppErrorCode_AUTHENTICATION_FAILED AppErrorCode = 2001
	AppErrorCode_PERMISSION_DENIED     AppErrorCode = 2002
	// Rate limiting and service availability
	AppErrorCode_RATE_LIMIT_EXCEEDED AppErrorCode = 3001
	AppErrorCode_SERVICE_UNAVAILABLE AppErrorCode = 3002
	// Internal errors
	AppErrorCode_INTERNAL_ERROR AppErrorCode = 9001
)

// Enum value maps for AppErrorCode.
var (
	AppErrorCode_name = map[int32]string{
		0:    "APP_ERROR_CODE_UNSPECIFIED",
		1:    "VALIDATION_FAILED",
		2:    "REQUIRED_FIELD",
		3:    "TOO_SHORT",
		4:    "TOO_LONG",
		5:    "INVALID_FORMAT",
		6:    "MUST_BE_FUTURE",
		7:    "INVALID_VALUE",
		8:    "DUPLICATE_TAG",
		9:    "INVALID_TAG_FORMAT",
		10:   "OVERDUE_COMPLETION",
		11:   "EMPTY_BATCH",
		12:   "BATCH_TOO_LARGE",
		13:   "DUPLICATE_TITLE",
		1001: "RESOURCE_NOT_FOUND",
		1002: "RESOURCE_CONFLICT",
		2001: "AUTHENTICATION_FAILED",
		2002: "PERMISSION_DENIED",
		3001: "RATE_LIMIT_EXCEEDED",
		3002: "SERVICE_UNAVAILABLE",
		9001: "INTERNAL_ERROR",
	}
	AppErrorCode_value = map[string]int32{
		"APP_ERROR_CODE_UNSPECIFIED": 0,
		"VALIDATION_FAILED":          1,
		"REQUIRED_FIELD":             2,
		"TOO_SHORT":                  3,
		"TOO_LONG":                   4,
		"INVALID_FORMAT":             5,
		"MUST_BE_FUTURE":             6,
		"INVALID_VALUE":              7,
		"DUPLICATE_TAG":              8,
		"INVALID_TAG_FORMAT":         9,
		"OVERDUE_COMPLETION":         10,
		"EMPTY_BATCH":                11,
		"BATCH_TOO_LARGE":            12,
		"DUPLICATE_TITLE":            13,
		"RESOURCE_NOT_FOUND":         1001,
		"RESOURCE_CONFLICT":          1002,
		"AUTHENTICATION_FAILED":      2001,
		"PERMISSION_DENIED":          2002,
		"RATE_LIMIT_EXCEEDED":        3001,
		"SERVICE_UNAVAILABLE":        3002,
		"INTERNAL_ERROR":             9001,
	}
)

func (x AppErrorCode) Enum() *AppErrorCode {
	p := new(AppErrorCode)
	*p = x
	return p
}

func (x AppErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_errors_v1_errors_proto_enumTypes[0].Descriptor()
}

func (AppErrorCode) Type() protoreflect.EnumType {
	return &file_api_proto_errors_v1_errors_proto_enumTypes[0]
}

func (x AppErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppErrorCode.Descriptor instead.
func (AppErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_errors_v1_errors_proto_rawDescGZIP(), []int{0}
}

// ErrorDetail provides a structured, machine-readable error payload.
// It is designed to be embedded in the `details` field of a `google.rpc.Status` message.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique, application-specific error code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// A short, human-readable summary of the problem type.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// A list of validation errors, useful for INVALID_ARGUMENT responses.
	FieldViolations []*FieldViolation `protobuf:"bytes,4,rep,name=field_violations,json=fieldViolations,proto3" json:"field_violations,omitempty"`
	// Optional trace ID for request correlation
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Optional timestamp when the error occurred
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional instance path where the error occurred
	Instance string `protobuf:"bytes,7,opt,name=instance,proto3" json:"instance,omitempty"`
	// Optional extensions for additional error context
	Extensions    map[string]*anypb.Any `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_api_proto_errors_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_errors_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_errors_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ErrorDetail) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ErrorDetail) GetFieldViolations() []*FieldViolation {
	if x != nil {
		return x.FieldViolations
	}
	return nil
}

func (x *ErrorDetail) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ErrorDetail) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ErrorDetail) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ErrorDetail) GetExtensions() map[string]*anypb.Any {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Describes a single validation failure.
type FieldViolation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path to the field that failed validation, e.g., "title".
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// A developer-facing description of the validation rule that failed.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Application-specific error code for this validation failure
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_api_proto_errors_v1_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_errors_v1_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_api_proto_errors_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldViolation) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_api_proto_errors_v1_errors_proto protoreflect.FileDescriptor

const file_api_proto_errors_v1_errors_proto_rawDesc = "" +
	"\n" +
	" api/proto/errors/v1/errors.proto\x12\terrors.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xa3\x03\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12D\n" +
	"\x10field_violations\x18\x04 \x03(\v2\x19.errors.v1.FieldViolationR\x0ffieldViolations\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\binstance\x18\a \x01(\tR\binstance\x12F\n" +
	"\n" +
	"extensions\x18\b \x03(\v2&.errors.v1.ErrorDetail.ExtensionsEntryR\n" +
	"extensions\x1aS\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\\\n" +
	"\x0eFieldViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code*\xdd\x03\n" +
	"\fAppErrorCode\x12\x1e\n" +
	"\x1aAPP_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VALIDATION_FAILED\x10\x01\x12\x12\n" +
	"\x0eREQUIRED_FIELD\x10\x02\x12\r\n" +
	"\tTOO_SHORT\x10\x03\x12\f\n" +
	"\bTOO_LONG\x10\x04\x12\x12\n" +
	"\x0eINVALID_FORMAT\x10\x05\x12\x12\n" +
	"\x0eMUST_BE_FUTURE\x10\x06\x12\x11\n" +
	"\rINVALID_VALUE\x10\a\x12\x11\n" +
	"\rDUPLICATE_TAG\x10\b\x12\x16\n" +
	"\x12INVALID_TAG_FORMAT\x10\t\x12\x16\n" +
	"\x12OVERDUE_COMPLETION\x10\n" +
	"\x12\x0f\n" +
	"\vEMPTY_BATCH\x10\v\x12\x13\n" +
	"\x0fBATCH_TOO_LARGE\x10\f\x12\x13\n" +
	"\x0fDUPLICATE_TITLE\x10\r\x12\x17\n" +
	"\x12RESOURCE_NOT_FOUND\x10\xe9\a\x12\x16\n" +
	"\x11RESOURCE_CONFLICT\x10\xea\a\x12\x1a\n" +
	"\x15AUTHENTICATION_FAILED\x10\xd1\x0f\x12\x16\n" +
	"\x11PERMISSION_DENIED\x10\xd2\x0f\x12\x18\n" +
	"\x13RATE_LIMIT_EXCEEDED\x10\xb9\x17\x12\x18\n" +
	"\x13SERVICE_UNAVAILABLE\x10\xba\x17\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xa9FB\xa5\x01\n" +
	"\rcom.errors.v1B\vErrorsProtoP\x01ZBgithub.com/bhatti/todo-api-errors/gen/api/proto/errors/v1;errorsv1\xa2\x02\x03EXX\xaa\x02\tErrors.V1\xca\x02\tErrors\\V1\xe2\x02\x15Errors\\V1\\GPBMetadata\xea\x02\n" +
	"Errors::V1b\x06proto3"

var (
	file_api_proto_errors_v1_errors_proto_rawDescOnce sync.Once
	file_api_proto_errors_v1_errors_proto_rawDescData []byte
)

func file_api_proto_errors_v1_errors_proto_rawDescGZIP() []byte {
	file_api_proto_errors_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_proto_errors_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_errors_v1_errors_proto_rawDesc), len(file_api_proto_errors_v1_errors_proto_rawDesc)))
	})
	return file_api_proto_errors_v1_errors_proto_rawDescData
}

var file_api_proto_errors_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_errors_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_errors_v1_errors_proto_goTypes = []any{
	(AppErrorCode)(0),             // 0: errors.v1.AppErrorCode
	(*ErrorDetail)(nil),           // 1: errors.v1.ErrorDetail
	(*FieldViolation)(nil),        // 2: errors.v1.FieldViolation
	nil,                           // 3: errors.v1.ErrorDetail.ExtensionsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
}
var file_api_proto_errors_v1_errors_proto_depIdxs = []int32{
	2, // 0: errors.v1.ErrorDetail.field_violations:type_name -> errors.v1.FieldViolation
	4, // 1: errors.v1.ErrorDetail.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: errors.v1.ErrorDetail.extensions:type_name -> errors.v1.ErrorDetail.ExtensionsEntry
	5, // 3: errors.v1.ErrorDetail.ExtensionsEntry.value:type_name -> google.protobuf.Any
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_errors_v1_errors_proto_init() }
func file_api_proto_errors_v1_errors_proto_init() {
	if File_api_proto_errors_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_errors_v1_errors_proto_rawDesc), len(file_api_proto_errors_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_errors_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_proto_errors_v1_errors_proto_depIdxs,
		EnumInfos:         file_api_proto_errors_v1_errors_proto_enumTypes,
		MessageInfos:      file_api_proto_errors_v1_errors_proto_msgTypes,
	}.Build()
	File_api_proto_errors_v1_errors_proto = out.File
	file_api_proto_errors_v1_errors_proto_goTypes = nil
	file_api_proto_errors_v1_errors_proto_depIdxs = nil
}
