// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/proto/todo/v1/todo.proto

package todov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task status enumeration
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1
	Status_STATUS_IN_PROGRESS Status = 2
	Status_STATUS_COMPLETED   Status = 3
	Status_STATUS_CANCELLED   Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_IN_PROGRESS",
		3: "STATUS_COMPLETED",
		4: "STATUS_CANCELLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_IN_PROGRESS": 2,
		"STATUS_COMPLETED":   3,
		"STATUS_CANCELLED":   4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_todo_v1_todo_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_proto_todo_v1_todo_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

// Task priority enumeration
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_MEDIUM      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_CRITICAL    Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_MEDIUM":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_CRITICAL":    4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_todo_v1_todo_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_api_proto_todo_v1_todo_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{1}
}

// Task represents a TODO item
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name of the task
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Task title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Task description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Task status
	Status Status `protobuf:"varint,4,opt,name=status,proto3,enum=todo.v1.Status" json:"status,omitempty"`
	// Task priority
	Priority Priority `protobuf:"varint,5,opt,name=priority,proto3,enum=todo.v1.Priority" json:"priority,omitempty"`
	// Due date for the task
	DueDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	// Task creation time
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Task last update time
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// User who created the task
	CreatedBy string `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// Tags associated with the task
	Tags          []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Task) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Task) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Task) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Task) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Task) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// CreateTaskRequest message
type CreateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task to create
	Task          *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// GetTaskRequest message
type GetTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name of the task
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListTasksRequest message
type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of tasks to return
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token for pagination
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter expression
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Order by expression
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTasksRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListTasksRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// ListTasksResponse message
type ListTasksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of tasks
	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// Token for next page
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of tasks
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTasksResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// UpdateTaskRequest message
type UpdateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task to update
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// Fields to update
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *UpdateTaskRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteTaskRequest message
type DeleteTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name of the task
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteTaskResponse message
type DeleteTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Confirmation message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// BatchCreateTasksRequest message
type BatchCreateTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tasks to create
	Requests      []*CreateTaskRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateTasksRequest) Reset() {
	*x = BatchCreateTasksRequest{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateTasksRequest) ProtoMessage() {}

func (x *BatchCreateTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateTasksRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCreateTasksRequest) GetRequests() []*CreateTaskRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// BatchCreateTasksResponse message
type BatchCreateTasksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created tasks
	Tasks         []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateTasksResponse) Reset() {
	*x = BatchCreateTasksResponse{}
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateTasksResponse) ProtoMessage() {}

func (x *BatchCreateTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_v1_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateTasksResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_v1_todo_proto_rawDescGZIP(), []int{9}
}

func (x *BatchCreateTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_api_proto_todo_v1_todo_proto protoreflect.FileDescriptor

const file_api_proto_todo_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/todo/v1/todo.proto\x12\atodo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1bbuf/validate/validate.proto\"\xac\x04\n" +
	"\x04Task\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xe0A\b\xe0A\x03R\x04name\x12#\n" +
	"\x05title\x18\x02 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xc8\x01R\x05title\x12,\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xe0A\x01\xbaH\x04r\x02\x18dR\vdescription\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0f.todo.v1.StatusB\x03\xe0A\x02R\x06status\x122\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x11.todo.v1.PriorityB\x03\xe0A\x01R\bpriority\x12B\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\v\xe0A\x01\xbaH\x05\xb2\x01\x02@\x01R\adueDate\x12@\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12\"\n" +
	"\n" +
	"created_by\x18\t \x01(\tB\x03\xe0A\x03R\tcreatedBy\x120\n" +
	"\x04tags\x18\n" +
	" \x03(\tB\x1c\xbaH\x19\x92\x01\x16\x10\n" +
	"\"\x12r\x10\x1822\f^[a-z0-9-]+$R\x04tags:5\xeaA2\n" +
	"\x15todo.example.com/Task\x12\ftasks/{task}*\x05tasks2\x04task\"A\n" +
	"\x11CreateTaskRequest\x12,\n" +
	"\x04task\x18\x01 \x01(\v2\r.todo.v1.TaskB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\x04task\"_\n" +
	"\x0eGetTaskRequest\x12M\n" +
	"\x04name\x18\x01 \x01(\tB9\xe0A\x02\xfaA\x17\n" +
	"\x15todo.example.com/Task\xbaH\x19r\x172\x15^tasks/[a-zA-Z0-9-]+$R\x04name\"\x8c\x01\n" +
	"\x10ListTasksRequest\x12&\n" +
	"\tpage_size\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\x7f\n" +
	"\x11ListTasksResponse\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.todo.v1.TaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"\x89\x01\n" +
	"\x11UpdateTaskRequest\x12,\n" +
	"\x04task\x18\x01 \x01(\v2\r.todo.v1.TaskB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\x04task\x12F\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\n" +
	"updateMask\"F\n" +
	"\x11DeleteTaskRequest\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xe0A\x02\xfaA\x17\n" +
	"\x15todo.example.com/TaskR\x04name\".\n" +
	"\x12DeleteTaskResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"`\n" +
	"\x17BatchCreateTasksRequest\x12E\n" +
	"\brequests\x18\x01 \x03(\v2\x1a.todo.v1.CreateTaskRequestB\r\xe0A\x02\xbaH\a\x92\x01\x04\b\x01\x10dR\brequests\"?\n" +
	"\x18BatchCreateTasksResponse\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.todo.v1.TaskR\x05tasks*x\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12STATUS_IN_PROGRESS\x10\x02\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x03\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x04*u\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x042\xc0\x04\n" +
	"\vTodoService\x12M\n" +
	"\n" +
	"CreateTask\x12\x1a.todo.v1.CreateTaskRequest\x1a\r.todo.v1.Task\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/tasks\x12M\n" +
	"\aGetTask\x12\x17.todo.v1.GetTaskRequest\x1a\r.todo.v1.Task\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/{name=tasks/*}\x12U\n" +
	"\tListTasks\x12\x19.todo.v1.ListTasksRequest\x1a\x1a.todo.v1.ListTasksResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/tasks\x12^\n" +
	"\n" +
	"UpdateTask\x12\x1a.todo.v1.UpdateTaskRequest\x1a\r.todo.v1.Task\"%\x82\xd3\xe4\x93\x02\x1f:\x04task2\x17/v1/{task.name=tasks/*}\x12a\n" +
	"\n" +
	"DeleteTask\x12\x1a.todo.v1.DeleteTaskRequest\x1a\x1b.todo.v1.DeleteTaskResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/{name=tasks/*}\x12y\n" +
	"\x10BatchCreateTasks\x12 .todo.v1.BatchCreateTasksRequest\x1a!.todo.v1.BatchCreateTasksResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/tasks:batchCreateB\x95\x01\n" +
	"\vcom.todo.v1B\tTodoProtoP\x01Z>github.com/bhatti/todo-api-errors/gen/api/proto/todo/v1;todov1\xa2\x02\x03TXX\xaa\x02\aTodo.V1\xca\x02\aTodo\\V1\xe2\x02\x13Todo\\V1\\GPBMetadata\xea\x02\bTodo::V1b\x06proto3"

var (
	file_api_proto_todo_v1_todo_proto_rawDescOnce sync.Once
	file_api_proto_todo_v1_todo_proto_rawDescData []byte
)

func file_api_proto_todo_v1_todo_proto_rawDescGZIP() []byte {
	file_api_proto_todo_v1_todo_proto_rawDescOnce.Do(func() {
		file_api_proto_todo_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_todo_v1_todo_proto_rawDesc), len(file_api_proto_todo_v1_todo_proto_rawDesc)))
	})
	return file_api_proto_todo_v1_todo_proto_rawDescData
}

var file_api_proto_todo_v1_todo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_todo_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_todo_v1_todo_proto_goTypes = []any{
	(Status)(0),                      // 0: todo.v1.Status
	(Priority)(0),                    // 1: todo.v1.Priority
	(*Task)(nil),                     // 2: todo.v1.Task
	(*CreateTaskRequest)(nil),        // 3: todo.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),           // 4: todo.v1.GetTaskRequest
	(*ListTasksRequest)(nil),         // 5: todo.v1.ListTasksRequest
	(*ListTasksResponse)(nil),        // 6: todo.v1.ListTasksResponse
	(*UpdateTaskRequest)(nil),        // 7: todo.v1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),        // 8: todo.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),       // 9: todo.v1.DeleteTaskResponse
	(*BatchCreateTasksRequest)(nil),  // 10: todo.v1.BatchCreateTasksRequest
	(*BatchCreateTasksResponse)(nil), // 11: todo.v1.BatchCreateTasksResponse
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),    // 13: google.protobuf.FieldMask
}
var file_api_proto_todo_v1_todo_proto_depIdxs = []int32{
	0,  // 0: todo.v1.Task.status:type_name -> todo.v1.Status
	1,  // 1: todo.v1.Task.priority:type_name -> todo.v1.Priority
	12, // 2: todo.v1.Task.due_date:type_name -> google.protobuf.Timestamp
	12, // 3: todo.v1.Task.create_time:type_name -> google.protobuf.Timestamp
	12, // 4: todo.v1.Task.update_time:type_name -> google.protobuf.Timestamp
	2,  // 5: todo.v1.CreateTaskRequest.task:type_name -> todo.v1.Task
	2,  // 6: todo.v1.ListTasksResponse.tasks:type_name -> todo.v1.Task
	2,  // 7: todo.v1.UpdateTaskRequest.task:type_name -> todo.v1.Task
	13, // 8: todo.v1.UpdateTaskRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 9: todo.v1.BatchCreateTasksRequest.requests:type_name -> todo.v1.CreateTaskRequest
	2,  // 10: todo.v1.BatchCreateTasksResponse.tasks:type_name -> todo.v1.Task
	3,  // 11: todo.v1.TodoService.CreateTask:input_type -> todo.v1.CreateTaskRequest
	4,  // 12: todo.v1.TodoService.GetTask:input_type -> todo.v1.GetTaskRequest
	5,  // 13: todo.v1.TodoService.ListTasks:input_type -> todo.v1.ListTasksRequest
	7,  // 14: todo.v1.TodoService.UpdateTask:input_type -> todo.v1.UpdateTaskRequest
	8,  // 15: todo.v1.TodoService.DeleteTask:input_type -> todo.v1.DeleteTaskRequest
	10, // 16: todo.v1.TodoService.BatchCreateTasks:input_type -> todo.v1.BatchCreateTasksRequest
	2,  // 17: todo.v1.TodoService.CreateTask:output_type -> todo.v1.Task
	2,  // 18: todo.v1.TodoService.GetTask:output_type -> todo.v1.Task
	6,  // 19: todo.v1.TodoService.ListTasks:output_type -> todo.v1.ListTasksResponse
	2,  // 20: todo.v1.TodoService.UpdateTask:output_type -> todo.v1.Task
	9,  // 21: todo.v1.TodoService.DeleteTask:output_type -> todo.v1.DeleteTaskResponse
	11, // 22: todo.v1.TodoService.BatchCreateTasks:output_type -> todo.v1.BatchCreateTasksResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_todo_v1_todo_proto_init() }
func file_api_proto_todo_v1_todo_proto_init() {
	if File_api_proto_todo_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_todo_v1_todo_proto_rawDesc), len(file_api_proto_todo_v1_todo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_todo_v1_todo_proto_goTypes,
		DependencyIndexes: file_api_proto_todo_v1_todo_proto_depIdxs,
		EnumInfos:         file_api_proto_todo_v1_todo_proto_enumTypes,
		MessageInfos:      file_api_proto_todo_v1_todo_proto_msgTypes,
	}.Build()
	File_api_proto_todo_v1_todo_proto = out.File
	file_api_proto_todo_v1_todo_proto_goTypes = nil
	file_api_proto_todo_v1_todo_proto_depIdxs = nil
}
