// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/pii/v1/account_without_annotations.proto

package piiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account status enum
type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACTIVE                     AccountStatus = 1
	AccountStatus_SUSPENDED                  AccountStatus = 2
	AccountStatus_CLOSED                     AccountStatus = 3
	AccountStatus_PENDING                    AccountStatus = 4
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "SUSPENDED",
		3: "CLOSED",
		4: "PENDING",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACTIVE":                     1,
		"SUSPENDED":                  2,
		"CLOSED":                     3,
		"PENDING":                    4,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_pii_v1_account_without_annotations_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_api_proto_pii_v1_account_without_annotations_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{0}
}

// Account represents a user account
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System fields
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Status        AccountStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=pii.v1.AccountStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Personal information
	FirstName   string `protobuf:"bytes,10,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    string `protobuf:"bytes,11,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MiddleName  string `protobuf:"bytes,12,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	DateOfBirth string `protobuf:"bytes,13,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"` // Format: YYYY-MM-DD
	Gender      string `protobuf:"bytes,14,opt,name=gender,proto3" json:"gender,omitempty"`
	// Contact information
	Email         string `protobuf:"bytes,20,opt,name=email,proto3" json:"email,omitempty"`
	PersonalEmail string `protobuf:"bytes,21,opt,name=personal_email,json=personalEmail,proto3" json:"personal_email,omitempty"`
	WorkEmail     string `protobuf:"bytes,22,opt,name=work_email,json=workEmail,proto3" json:"work_email,omitempty"`
	Phone         string `protobuf:"bytes,23,opt,name=phone,proto3" json:"phone,omitempty"`
	MobilePhone   string `protobuf:"bytes,24,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	WorkPhone     string `protobuf:"bytes,25,opt,name=work_phone,json=workPhone,proto3" json:"work_phone,omitempty"`
	// Address information
	HomeAddress    *Address `protobuf:"bytes,30,opt,name=home_address,json=homeAddress,proto3" json:"home_address,omitempty"`
	WorkAddress    *Address `protobuf:"bytes,31,opt,name=work_address,json=workAddress,proto3" json:"work_address,omitempty"`
	MailingAddress *Address `protobuf:"bytes,32,opt,name=mailing_address,json=mailingAddress,proto3" json:"mailing_address,omitempty"`
	// Government IDs
	Ssn            string `protobuf:"bytes,40,opt,name=ssn,proto3" json:"ssn,omitempty"`
	TaxId          string `protobuf:"bytes,41,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	PassportNumber string `protobuf:"bytes,42,opt,name=passport_number,json=passportNumber,proto3" json:"passport_number,omitempty"`
	DriversLicense string `protobuf:"bytes,43,opt,name=drivers_license,json=driversLicense,proto3" json:"drivers_license,omitempty"`
	NationalId     string `protobuf:"bytes,44,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	// Financial information
	BankAccountNumber string  `protobuf:"bytes,50,opt,name=bank_account_number,json=bankAccountNumber,proto3" json:"bank_account_number,omitempty"`
	RoutingNumber     string  `protobuf:"bytes,51,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	CreditCardNumber  string  `protobuf:"bytes,52,opt,name=credit_card_number,json=creditCardNumber,proto3" json:"credit_card_number,omitempty"`
	CreditCardCvv     string  `protobuf:"bytes,53,opt,name=credit_card_cvv,json=creditCardCvv,proto3" json:"credit_card_cvv,omitempty"`
	CreditCardExpiry  string  `protobuf:"bytes,54,opt,name=credit_card_expiry,json=creditCardExpiry,proto3" json:"credit_card_expiry,omitempty"`
	AnnualIncome      float64 `protobuf:"fixed64,55,opt,name=annual_income,json=annualIncome,proto3" json:"annual_income,omitempty"`
	CreditScore       int32   `protobuf:"varint,56,opt,name=credit_score,json=creditScore,proto3" json:"credit_score,omitempty"`
	// Employment information
	EmployerName string  `protobuf:"bytes,60,opt,name=employer_name,json=employerName,proto3" json:"employer_name,omitempty"`
	JobTitle     string  `protobuf:"bytes,61,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	EmployeeId   string  `protobuf:"bytes,62,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Salary       float64 `protobuf:"fixed64,63,opt,name=salary,proto3" json:"salary,omitempty"`
	// Medical information
	MedicalRecordNumber string   `protobuf:"bytes,70,opt,name=medical_record_number,json=medicalRecordNumber,proto3" json:"medical_record_number,omitempty"`
	HealthInsuranceId   string   `protobuf:"bytes,71,opt,name=health_insurance_id,json=healthInsuranceId,proto3" json:"health_insurance_id,omitempty"`
	MedicalConditions   []string `protobuf:"bytes,72,rep,name=medical_conditions,json=medicalConditions,proto3" json:"medical_conditions,omitempty"`
	Prescriptions       []string `protobuf:"bytes,73,rep,name=prescriptions,proto3" json:"prescriptions,omitempty"`
	// Authentication
	Username         string `protobuf:"bytes,80,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash     string `protobuf:"bytes,81,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	SecurityQuestion string `protobuf:"bytes,82,opt,name=security_question,json=securityQuestion,proto3" json:"security_question,omitempty"`
	SecurityAnswer   string `protobuf:"bytes,83,opt,name=security_answer,json=securityAnswer,proto3" json:"security_answer,omitempty"`
	ApiKey           string `protobuf:"bytes,84,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	AccessToken      string `protobuf:"bytes,85,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Device information
	IpAddress    string    `protobuf:"bytes,90,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	DeviceId     string    `protobuf:"bytes,91,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserAgent    string    `protobuf:"bytes,92,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	LastLocation *Location `protobuf:"bytes,93,opt,name=last_location,json=lastLocation,proto3" json:"last_location,omitempty"`
	// Additional fields
	Metadata      map[string]string `protobuf:"bytes,100,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string          `protobuf:"bytes,101,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Account) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Account) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Account) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *Account) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Account) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetPersonalEmail() string {
	if x != nil {
		return x.PersonalEmail
	}
	return ""
}

func (x *Account) GetWorkEmail() string {
	if x != nil {
		return x.WorkEmail
	}
	return ""
}

func (x *Account) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Account) GetMobilePhone() string {
	if x != nil {
		return x.MobilePhone
	}
	return ""
}

func (x *Account) GetWorkPhone() string {
	if x != nil {
		return x.WorkPhone
	}
	return ""
}

func (x *Account) GetHomeAddress() *Address {
	if x != nil {
		return x.HomeAddress
	}
	return nil
}

func (x *Account) GetWorkAddress() *Address {
	if x != nil {
		return x.WorkAddress
	}
	return nil
}

func (x *Account) GetMailingAddress() *Address {
	if x != nil {
		return x.MailingAddress
	}
	return nil
}

func (x *Account) GetSsn() string {
	if x != nil {
		return x.Ssn
	}
	return ""
}

func (x *Account) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *Account) GetPassportNumber() string {
	if x != nil {
		return x.PassportNumber
	}
	return ""
}

func (x *Account) GetDriversLicense() string {
	if x != nil {
		return x.DriversLicense
	}
	return ""
}

func (x *Account) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

func (x *Account) GetBankAccountNumber() string {
	if x != nil {
		return x.BankAccountNumber
	}
	return ""
}

func (x *Account) GetRoutingNumber() string {
	if x != nil {
		return x.RoutingNumber
	}
	return ""
}

func (x *Account) GetCreditCardNumber() string {
	if x != nil {
		return x.CreditCardNumber
	}
	return ""
}

func (x *Account) GetCreditCardCvv() string {
	if x != nil {
		return x.CreditCardCvv
	}
	return ""
}

func (x *Account) GetCreditCardExpiry() string {
	if x != nil {
		return x.CreditCardExpiry
	}
	return ""
}

func (x *Account) GetAnnualIncome() float64 {
	if x != nil {
		return x.AnnualIncome
	}
	return 0
}

func (x *Account) GetCreditScore() int32 {
	if x != nil {
		return x.CreditScore
	}
	return 0
}

func (x *Account) GetEmployerName() string {
	if x != nil {
		return x.EmployerName
	}
	return ""
}

func (x *Account) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *Account) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *Account) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *Account) GetMedicalRecordNumber() string {
	if x != nil {
		return x.MedicalRecordNumber
	}
	return ""
}

func (x *Account) GetHealthInsuranceId() string {
	if x != nil {
		return x.HealthInsuranceId
	}
	return ""
}

func (x *Account) GetMedicalConditions() []string {
	if x != nil {
		return x.MedicalConditions
	}
	return nil
}

func (x *Account) GetPrescriptions() []string {
	if x != nil {
		return x.Prescriptions
	}
	return nil
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *Account) GetSecurityQuestion() string {
	if x != nil {
		return x.SecurityQuestion
	}
	return ""
}

func (x *Account) GetSecurityAnswer() string {
	if x != nil {
		return x.SecurityAnswer
	}
	return ""
}

func (x *Account) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Account) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Account) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Account) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Account) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Account) GetLastLocation() *Location {
	if x != nil {
		return x.LastLocation
	}
	return nil
}

func (x *Account) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Account) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Address message
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreetLine1   string                 `protobuf:"bytes,1,opt,name=street_line1,json=streetLine1,proto3" json:"street_line1,omitempty"`
	StreetLine2   string                 `protobuf:"bytes,2,opt,name=street_line2,json=streetLine2,proto3" json:"street_line2,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreetLine1() string {
	if x != nil {
		return x.StreetLine1
	}
	return ""
}

func (x *Address) GetStreetLine2() string {
	if x != nil {
		return x.StreetLine2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// Location for geolocation data
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *Location) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Account        *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CreateAccountRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetAccountRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeSensitiveData bool                   `protobuf:"varint,2,opt,name=include_sensitive_data,json=includeSensitiveData,proto3" json:"include_sensitive_data,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAccountRequest) GetIncludeSensitiveData() bool {
	if x != nil {
		return x.IncludeSensitiveData
	}
	return false
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *UpdateAccountRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAccountRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{7}
}

func (x *ListAccountsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAccountsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAccountsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAccountsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{8}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ListAccountsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAccountsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SearchAccountsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search by various fields (all potentially PII)
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone       string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Ssn         string `protobuf:"bytes,4,opt,name=ssn,proto3" json:"ssn,omitempty"`
	DateOfBirth string `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	// Pagination
	PageSize      int32  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAccountsRequest) Reset() {
	*x = SearchAccountsRequest{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAccountsRequest) ProtoMessage() {}

func (x *SearchAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAccountsRequest.ProtoReflect.Descriptor instead.
func (*SearchAccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{9}
}

func (x *SearchAccountsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchAccountsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SearchAccountsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SearchAccountsRequest) GetSsn() string {
	if x != nil {
		return x.Ssn
	}
	return ""
}

func (x *SearchAccountsRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *SearchAccountsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchAccountsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type SearchAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalMatches  int32                  `protobuf:"varint,3,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAccountsResponse) Reset() {
	*x = SearchAccountsResponse{}
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAccountsResponse) ProtoMessage() {}

func (x *SearchAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pii_v1_account_without_annotations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAccountsResponse.ProtoReflect.Descriptor instead.
func (*SearchAccountsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP(), []int{10}
}

func (x *SearchAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *SearchAccountsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *SearchAccountsResponse) GetTotalMatches() int32 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

var File_api_proto_pii_v1_account_without_annotations_proto protoreflect.FileDescriptor

const file_api_proto_pii_v1_account_without_annotations_proto_rawDesc = "" +
	"\n" +
	"2api/proto/pii/v1/account_without_annotations.proto\x12\x06pii.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb8\x0f\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.pii.v1.AccountStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"first_name\x18\n" +
	" \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\v \x01(\tR\blastName\x12\x1f\n" +
	"\vmiddle_name\x18\f \x01(\tR\n" +
	"middleName\x12\"\n" +
	"\rdate_of_birth\x18\r \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x0e \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x14 \x01(\tR\x05email\x12%\n" +
	"\x0epersonal_email\x18\x15 \x01(\tR\rpersonalEmail\x12\x1d\n" +
	"\n" +
	"work_email\x18\x16 \x01(\tR\tworkEmail\x12\x14\n" +
	"\x05phone\x18\x17 \x01(\tR\x05phone\x12!\n" +
	"\fmobile_phone\x18\x18 \x01(\tR\vmobilePhone\x12\x1d\n" +
	"\n" +
	"work_phone\x18\x19 \x01(\tR\tworkPhone\x122\n" +
	"\fhome_address\x18\x1e \x01(\v2\x0f.pii.v1.AddressR\vhomeAddress\x122\n" +
	"\fwork_address\x18\x1f \x01(\v2\x0f.pii.v1.AddressR\vworkAddress\x128\n" +
	"\x0fmailing_address\x18  \x01(\v2\x0f.pii.v1.AddressR\x0emailingAddress\x12\x10\n" +
	"\x03ssn\x18( \x01(\tR\x03ssn\x12\x15\n" +
	"\x06tax_id\x18) \x01(\tR\x05taxId\x12'\n" +
	"\x0fpassport_number\x18* \x01(\tR\x0epassportNumber\x12'\n" +
	"\x0fdrivers_license\x18+ \x01(\tR\x0edriversLicense\x12\x1f\n" +
	"\vnational_id\x18, \x01(\tR\n" +
	"nationalId\x12.\n" +
	"\x13bank_account_number\x182 \x01(\tR\x11bankAccountNumber\x12%\n" +
	"\x0erouting_number\x183 \x01(\tR\rroutingNumber\x12,\n" +
	"\x12credit_card_number\x184 \x01(\tR\x10creditCardNumber\x12&\n" +
	"\x0fcredit_card_cvv\x185 \x01(\tR\rcreditCardCvv\x12,\n" +
	"\x12credit_card_expiry\x186 \x01(\tR\x10creditCardExpiry\x12#\n" +
	"\rannual_income\x187 \x01(\x01R\fannualIncome\x12!\n" +
	"\fcredit_score\x188 \x01(\x05R\vcreditScore\x12#\n" +
	"\remployer_name\x18< \x01(\tR\femployerName\x12\x1b\n" +
	"\tjob_title\x18= \x01(\tR\bjobTitle\x12\x1f\n" +
	"\vemployee_id\x18> \x01(\tR\n" +
	"employeeId\x12\x16\n" +
	"\x06salary\x18? \x01(\x01R\x06salary\x122\n" +
	"\x15medical_record_number\x18F \x01(\tR\x13medicalRecordNumber\x12.\n" +
	"\x13health_insurance_id\x18G \x01(\tR\x11healthInsuranceId\x12-\n" +
	"\x12medical_conditions\x18H \x03(\tR\x11medicalConditions\x12$\n" +
	"\rprescriptions\x18I \x03(\tR\rprescriptions\x12\x1a\n" +
	"\busername\x18P \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18Q \x01(\tR\fpasswordHash\x12+\n" +
	"\x11security_question\x18R \x01(\tR\x10securityQuestion\x12'\n" +
	"\x0fsecurity_answer\x18S \x01(\tR\x0esecurityAnswer\x12\x17\n" +
	"\aapi_key\x18T \x01(\tR\x06apiKey\x12!\n" +
	"\faccess_token\x18U \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"ip_address\x18Z \x01(\tR\tipAddress\x12\x1b\n" +
	"\tdevice_id\x18[ \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\\ \x01(\tR\tuserAgent\x125\n" +
	"\rlast_location\x18] \x01(\v2\x10.pii.v1.LocationR\flastLocation\x129\n" +
	"\bmetadata\x18d \x03(\v2\x1d.pii.v1.Account.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18e \x03(\tR\x04tags\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\aAddress\x12!\n" +
	"\fstreet_line1\x18\x01 \x01(\tR\vstreetLine1\x12!\n" +
	"\fstreet_line2\x18\x02 \x01(\tR\vstreetLine2\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\"\x9a\x01\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"j\n" +
	"\x14CreateAccountRequest\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.pii.v1.AccountR\aaccount\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"Y\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x16include_sensitive_data\x18\x02 \x01(\bR\x14includeSensitiveData\"~\n" +
	"\x14UpdateAccountRequest\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.pii.v1.AccountR\aaccount\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"G\n" +
	"\x14DeleteAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\"\x84\x01\n" +
	"\x13ListAccountsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\x8c\x01\n" +
	"\x14ListAccountsResponse\x12+\n" +
	"\baccounts\x18\x01 \x03(\v2\x0f.pii.v1.AccountR\baccounts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xc9\x01\n" +
	"\x15SearchAccountsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x10\n" +
	"\x03ssn\x18\x04 \x01(\tR\x03ssn\x12\"\n" +
	"\rdate_of_birth\x18\x05 \x01(\tR\vdateOfBirth\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"\x92\x01\n" +
	"\x16SearchAccountsResponse\x12+\n" +
	"\baccounts\x18\x01 \x03(\v2\x0f.pii.v1.AccountR\baccounts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12#\n" +
	"\rtotal_matches\x18\x03 \x01(\x05R\ftotalMatches*c\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tSUSPENDED\x10\x02\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x03\x12\v\n" +
	"\aPENDING\x10\x042\xad\x03\n" +
	"\x0eAccountService\x12>\n" +
	"\rCreateAccount\x12\x1c.pii.v1.CreateAccountRequest\x1a\x0f.pii.v1.Account\x128\n" +
	"\n" +
	"GetAccount\x12\x19.pii.v1.GetAccountRequest\x1a\x0f.pii.v1.Account\x12>\n" +
	"\rUpdateAccount\x12\x1c.pii.v1.UpdateAccountRequest\x1a\x0f.pii.v1.Account\x12E\n" +
	"\rDeleteAccount\x12\x1c.pii.v1.DeleteAccountRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\fListAccounts\x12\x1b.pii.v1.ListAccountsRequest\x1a\x1c.pii.v1.ListAccountsResponse\x12O\n" +
	"\x0eSearchAccounts\x12\x1d.pii.v1.SearchAccountsRequest\x1a\x1e.pii.v1.SearchAccountsResponseB\xa3\x01\n" +
	"\n" +
	"com.pii.v1B\x1eAccountWithoutAnnotationsProtoP\x01Z<github.com/bhatti/todo-api-errors/gen/api/proto/pii/v1;piiv1\xa2\x02\x03PXX\xaa\x02\x06Pii.V1\xca\x02\x06Pii\\V1\xe2\x02\x12Pii\\V1\\GPBMetadata\xea\x02\aPii::V1b\x06proto3"

var (
	file_api_proto_pii_v1_account_without_annotations_proto_rawDescOnce sync.Once
	file_api_proto_pii_v1_account_without_annotations_proto_rawDescData []byte
)

func file_api_proto_pii_v1_account_without_annotations_proto_rawDescGZIP() []byte {
	file_api_proto_pii_v1_account_without_annotations_proto_rawDescOnce.Do(func() {
		file_api_proto_pii_v1_account_without_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_pii_v1_account_without_annotations_proto_rawDesc), len(file_api_proto_pii_v1_account_without_annotations_proto_rawDesc)))
	})
	return file_api_proto_pii_v1_account_without_annotations_proto_rawDescData
}

var file_api_proto_pii_v1_account_without_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_pii_v1_account_without_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_pii_v1_account_without_annotations_proto_goTypes = []any{
	(AccountStatus)(0),             // 0: pii.v1.AccountStatus
	(*Account)(nil),                // 1: pii.v1.Account
	(*Address)(nil),                // 2: pii.v1.Address
	(*Location)(nil),               // 3: pii.v1.Location
	(*CreateAccountRequest)(nil),   // 4: pii.v1.CreateAccountRequest
	(*GetAccountRequest)(nil),      // 5: pii.v1.GetAccountRequest
	(*UpdateAccountRequest)(nil),   // 6: pii.v1.UpdateAccountRequest
	(*DeleteAccountRequest)(nil),   // 7: pii.v1.DeleteAccountRequest
	(*ListAccountsRequest)(nil),    // 8: pii.v1.ListAccountsRequest
	(*ListAccountsResponse)(nil),   // 9: pii.v1.ListAccountsResponse
	(*SearchAccountsRequest)(nil),  // 10: pii.v1.SearchAccountsRequest
	(*SearchAccountsResponse)(nil), // 11: pii.v1.SearchAccountsResponse
	nil,                            // 12: pii.v1.Account.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),  // 14: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_api_proto_pii_v1_account_without_annotations_proto_depIdxs = []int32{
	0,  // 0: pii.v1.Account.status:type_name -> pii.v1.AccountStatus
	13, // 1: pii.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: pii.v1.Account.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: pii.v1.Account.home_address:type_name -> pii.v1.Address
	2,  // 4: pii.v1.Account.work_address:type_name -> pii.v1.Address
	2,  // 5: pii.v1.Account.mailing_address:type_name -> pii.v1.Address
	3,  // 6: pii.v1.Account.last_location:type_name -> pii.v1.Location
	12, // 7: pii.v1.Account.metadata:type_name -> pii.v1.Account.MetadataEntry
	13, // 8: pii.v1.Location.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 9: pii.v1.CreateAccountRequest.account:type_name -> pii.v1.Account
	1,  // 10: pii.v1.UpdateAccountRequest.account:type_name -> pii.v1.Account
	14, // 11: pii.v1.UpdateAccountRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 12: pii.v1.ListAccountsResponse.accounts:type_name -> pii.v1.Account
	1,  // 13: pii.v1.SearchAccountsResponse.accounts:type_name -> pii.v1.Account
	4,  // 14: pii.v1.AccountService.CreateAccount:input_type -> pii.v1.CreateAccountRequest
	5,  // 15: pii.v1.AccountService.GetAccount:input_type -> pii.v1.GetAccountRequest
	6,  // 16: pii.v1.AccountService.UpdateAccount:input_type -> pii.v1.UpdateAccountRequest
	7,  // 17: pii.v1.AccountService.DeleteAccount:input_type -> pii.v1.DeleteAccountRequest
	8,  // 18: pii.v1.AccountService.ListAccounts:input_type -> pii.v1.ListAccountsRequest
	10, // 19: pii.v1.AccountService.SearchAccounts:input_type -> pii.v1.SearchAccountsRequest
	1,  // 20: pii.v1.AccountService.CreateAccount:output_type -> pii.v1.Account
	1,  // 21: pii.v1.AccountService.GetAccount:output_type -> pii.v1.Account
	1,  // 22: pii.v1.AccountService.UpdateAccount:output_type -> pii.v1.Account
	15, // 23: pii.v1.AccountService.DeleteAccount:output_type -> google.protobuf.Empty
	9,  // 24: pii.v1.AccountService.ListAccounts:output_type -> pii.v1.ListAccountsResponse
	11, // 25: pii.v1.AccountService.SearchAccounts:output_type -> pii.v1.SearchAccountsResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_pii_v1_account_without_annotations_proto_init() }
func file_api_proto_pii_v1_account_without_annotations_proto_init() {
	if File_api_proto_pii_v1_account_without_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_pii_v1_account_without_annotations_proto_rawDesc), len(file_api_proto_pii_v1_account_without_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_pii_v1_account_without_annotations_proto_goTypes,
		DependencyIndexes: file_api_proto_pii_v1_account_without_annotations_proto_depIdxs,
		EnumInfos:         file_api_proto_pii_v1_account_without_annotations_proto_enumTypes,
		MessageInfos:      file_api_proto_pii_v1_account_without_annotations_proto_msgTypes,
	}.Build()
	File_api_proto_pii_v1_account_without_annotations_proto = out.File
	file_api_proto_pii_v1_account_without_annotations_proto_goTypes = nil
	file_api_proto_pii_v1_account_without_annotations_proto_depIdxs = nil
}
