// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/proto/pii/v1/sensitivity.proto

package piiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SensitivityLevel provides a simplified 4-tier classification for PII data
type SensitivityLevel int32

const (
	// Default - sensitivity not specified
	SensitivityLevel_SENSITIVITY_UNSPECIFIED SensitivityLevel = 0
	// PUBLIC - Non-sensitive public data
	// Examples: Company name, public product info, non-personal metadata
	SensitivityLevel_PUBLIC SensitivityLevel = 1
	// LOW - Low sensitivity personal data
	// Examples: Name, job title, work email, work address
	SensitivityLevel_LOW SensitivityLevel = 2
	// MEDIUM - Moderate sensitivity personal data
	// Examples: Personal email, phone, date of birth, home address
	SensitivityLevel_MEDIUM SensitivityLevel = 3
	// HIGH - Highly sensitive personal data
	// Examples: SSN, credit card, bank account, medical records, passwords
	SensitivityLevel_HIGH SensitivityLevel = 4
)

// Enum value maps for SensitivityLevel.
var (
	SensitivityLevel_name = map[int32]string{
		0: "SENSITIVITY_UNSPECIFIED",
		1: "PUBLIC",
		2: "LOW",
		3: "MEDIUM",
		4: "HIGH",
	}
	SensitivityLevel_value = map[string]int32{
		"SENSITIVITY_UNSPECIFIED": 0,
		"PUBLIC":                  1,
		"LOW":                     2,
		"MEDIUM":                  3,
		"HIGH":                    4,
	}
)

func (x SensitivityLevel) Enum() *SensitivityLevel {
	p := new(SensitivityLevel)
	*p = x
	return p
}

func (x SensitivityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensitivityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_pii_v1_sensitivity_proto_enumTypes[0].Descriptor()
}

func (SensitivityLevel) Type() protoreflect.EnumType {
	return &file_api_proto_pii_v1_sensitivity_proto_enumTypes[0]
}

func (x SensitivityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SensitivityLevel.Descriptor instead.
func (SensitivityLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_sensitivity_proto_rawDescGZIP(), []int{0}
}

// PiiType categorizes specific types of PII
type PiiType int32

const (
	PiiType_PII_TYPE_UNSPECIFIED PiiType = 0
	// Basic Identity
	PiiType_NAME          PiiType = 1 // Full name, first/last name
	PiiType_DATE_OF_BIRTH PiiType = 2 // Birth date
	PiiType_GENDER        PiiType = 3 // Gender identity
	// Contact Information
	PiiType_EMAIL_PERSONAL PiiType = 4 // Personal email
	PiiType_EMAIL_WORK     PiiType = 5 // Work email
	PiiType_PHONE_PERSONAL PiiType = 6 // Personal phone
	PiiType_PHONE_WORK     PiiType = 7 // Work phone
	PiiType_ADDRESS_HOME   PiiType = 8 // Home address
	PiiType_ADDRESS_WORK   PiiType = 9 // Work address
	// Government IDs
	PiiType_SSN             PiiType = 10 // Social Security Number
	PiiType_TAX_ID          PiiType = 11 // Tax ID (EIN, ITIN)
	PiiType_PASSPORT        PiiType = 12 // Passport number
	PiiType_DRIVERS_LICENSE PiiType = 13 // Driver's license
	PiiType_NATIONAL_ID     PiiType = 14 // National ID card
	// Financial
	PiiType_BANK_ACCOUNT   PiiType = 15 // Bank account number
	PiiType_CREDIT_CARD    PiiType = 16 // Credit card number
	PiiType_ROUTING_NUMBER PiiType = 17 // Bank routing number
	// Medical
	PiiType_MEDICAL_RECORD   PiiType = 18 // Medical record number
	PiiType_HEALTH_INSURANCE PiiType = 19 // Health insurance ID
	// Authentication
	PiiType_PASSWORD PiiType = 20 // Password/passphrase
	PiiType_API_KEY  PiiType = 21 // API keys/tokens
	// Device/Network
	PiiType_IP_ADDRESS PiiType = 22 // IP address
	PiiType_DEVICE_ID  PiiType = 23 // Device identifier
	// Account
	PiiType_USERNAME    PiiType = 24 // Username/login ID
	PiiType_CUSTOMER_ID PiiType = 25 // Customer/account ID
)

// Enum value maps for PiiType.
var (
	PiiType_name = map[int32]string{
		0:  "PII_TYPE_UNSPECIFIED",
		1:  "NAME",
		2:  "DATE_OF_BIRTH",
		3:  "GENDER",
		4:  "EMAIL_PERSONAL",
		5:  "EMAIL_WORK",
		6:  "PHONE_PERSONAL",
		7:  "PHONE_WORK",
		8:  "ADDRESS_HOME",
		9:  "ADDRESS_WORK",
		10: "SSN",
		11: "TAX_ID",
		12: "PASSPORT",
		13: "DRIVERS_LICENSE",
		14: "NATIONAL_ID",
		15: "BANK_ACCOUNT",
		16: "CREDIT_CARD",
		17: "ROUTING_NUMBER",
		18: "MEDICAL_RECORD",
		19: "HEALTH_INSURANCE",
		20: "PASSWORD",
		21: "API_KEY",
		22: "IP_ADDRESS",
		23: "DEVICE_ID",
		24: "USERNAME",
		25: "CUSTOMER_ID",
	}
	PiiType_value = map[string]int32{
		"PII_TYPE_UNSPECIFIED": 0,
		"NAME":                 1,
		"DATE_OF_BIRTH":        2,
		"GENDER":               3,
		"EMAIL_PERSONAL":       4,
		"EMAIL_WORK":           5,
		"PHONE_PERSONAL":       6,
		"PHONE_WORK":           7,
		"ADDRESS_HOME":         8,
		"ADDRESS_WORK":         9,
		"SSN":                  10,
		"TAX_ID":               11,
		"PASSPORT":             12,
		"DRIVERS_LICENSE":      13,
		"NATIONAL_ID":          14,
		"BANK_ACCOUNT":         15,
		"CREDIT_CARD":          16,
		"ROUTING_NUMBER":       17,
		"MEDICAL_RECORD":       18,
		"HEALTH_INSURANCE":     19,
		"PASSWORD":             20,
		"API_KEY":              21,
		"IP_ADDRESS":           22,
		"DEVICE_ID":            23,
		"USERNAME":             24,
		"CUSTOMER_ID":          25,
	}
)

func (x PiiType) Enum() *PiiType {
	p := new(PiiType)
	*p = x
	return p
}

func (x PiiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PiiType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_pii_v1_sensitivity_proto_enumTypes[1].Descriptor()
}

func (PiiType) Type() protoreflect.EnumType {
	return &file_api_proto_pii_v1_sensitivity_proto_enumTypes[1]
}

func (x PiiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PiiType.Descriptor instead.
func (PiiType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_pii_v1_sensitivity_proto_rawDescGZIP(), []int{1}
}

var file_api_proto_pii_v1_sensitivity_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*SensitivityLevel)(nil),
		Field:         70000,
		Name:          "pii.v1.sensitivity",
		Tag:           "varint,70000,opt,name=sensitivity,enum=pii.v1.SensitivityLevel",
		Filename:      "api/proto/pii/v1/sensitivity.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*PiiType)(nil),
		Field:         70001,
		Name:          "pii.v1.pii_type",
		Tag:           "varint,70001,opt,name=pii_type,enum=pii.v1.PiiType",
		Filename:      "api/proto/pii/v1/sensitivity.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]PiiType)(nil),
		Field:         70002,
		Name:          "pii.v1.pii_types",
		Tag:           "varint,70002,rep,packed,name=pii_types,enum=pii.v1.PiiType",
		Filename:      "api/proto/pii/v1/sensitivity.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*SensitivityLevel)(nil),
		Field:         70003,
		Name:          "pii.v1.method_sensitivity",
		Tag:           "varint,70003,opt,name=method_sensitivity,enum=pii.v1.SensitivityLevel",
		Filename:      "api/proto/pii/v1/sensitivity.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70004,
		Name:          "pii.v1.audit_pii_access",
		Tag:           "varint,70004,opt,name=audit_pii_access",
		Filename:      "api/proto/pii/v1/sensitivity.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*SensitivityLevel)(nil),
		Field:         70005,
		Name:          "pii.v1.message_sensitivity",
		Tag:           "varint,70005,opt,name=message_sensitivity,enum=pii.v1.SensitivityLevel",
		Filename:      "api/proto/pii/v1/sensitivity.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Sensitivity level of the field
	//
	// optional pii.v1.SensitivityLevel sensitivity = 70000;
	E_Sensitivity = &file_api_proto_pii_v1_sensitivity_proto_extTypes[0]
	// Type of PII in this field
	//
	// optional pii.v1.PiiType pii_type = 70001;
	E_PiiType = &file_api_proto_pii_v1_sensitivity_proto_extTypes[1]
	// Multiple PII types if field contains composite data
	//
	// repeated pii.v1.PiiType pii_types = 70002;
	E_PiiTypes = &file_api_proto_pii_v1_sensitivity_proto_extTypes[2]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Highest sensitivity level returned by this method
	//
	// optional pii.v1.SensitivityLevel method_sensitivity = 70003;
	E_MethodSensitivity = &file_api_proto_pii_v1_sensitivity_proto_extTypes[3]
	// Whether this method requires PII audit logging
	//
	// optional bool audit_pii_access = 70004;
	E_AuditPiiAccess = &file_api_proto_pii_v1_sensitivity_proto_extTypes[4]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Highest sensitivity level in this message
	//
	// optional pii.v1.SensitivityLevel message_sensitivity = 70005;
	E_MessageSensitivity = &file_api_proto_pii_v1_sensitivity_proto_extTypes[5]
)

var File_api_proto_pii_v1_sensitivity_proto protoreflect.FileDescriptor

const file_api_proto_pii_v1_sensitivity_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/pii/v1/sensitivity.proto\x12\x06pii.v1\x1a google/protobuf/descriptor.proto*Z\n" +
	"\x10SensitivityLevel\x12\x1b\n" +
	"\x17SENSITIVITY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\a\n" +
	"\x03LOW\x10\x02\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x03\x12\b\n" +
	"\x04HIGH\x10\x04*\xbb\x03\n" +
	"\aPiiType\x12\x18\n" +
	"\x14PII_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NAME\x10\x01\x12\x11\n" +
	"\rDATE_OF_BIRTH\x10\x02\x12\n" +
	"\n" +
	"\x06GENDER\x10\x03\x12\x12\n" +
	"\x0eEMAIL_PERSONAL\x10\x04\x12\x0e\n" +
	"\n" +
	"EMAIL_WORK\x10\x05\x12\x12\n" +
	"\x0ePHONE_PERSONAL\x10\x06\x12\x0e\n" +
	"\n" +
	"PHONE_WORK\x10\a\x12\x10\n" +
	"\fADDRESS_HOME\x10\b\x12\x10\n" +
	"\fADDRESS_WORK\x10\t\x12\a\n" +
	"\x03SSN\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06TAX_ID\x10\v\x12\f\n" +
	"\bPASSPORT\x10\f\x12\x13\n" +
	"\x0fDRIVERS_LICENSE\x10\r\x12\x0f\n" +
	"\vNATIONAL_ID\x10\x0e\x12\x10\n" +
	"\fBANK_ACCOUNT\x10\x0f\x12\x0f\n" +
	"\vCREDIT_CARD\x10\x10\x12\x12\n" +
	"\x0eROUTING_NUMBER\x10\x11\x12\x12\n" +
	"\x0eMEDICAL_RECORD\x10\x12\x12\x14\n" +
	"\x10HEALTH_INSURANCE\x10\x13\x12\f\n" +
	"\bPASSWORD\x10\x14\x12\v\n" +
	"\aAPI_KEY\x10\x15\x12\x0e\n" +
	"\n" +
	"IP_ADDRESS\x10\x16\x12\r\n" +
	"\tDEVICE_ID\x10\x17\x12\f\n" +
	"\bUSERNAME\x10\x18\x12\x0f\n" +
	"\vCUSTOMER_ID\x10\x19:[\n" +
	"\vsensitivity\x12\x1d.google.protobuf.FieldOptions\x18\xf0\xa2\x04 \x01(\x0e2\x18.pii.v1.SensitivityLevelR\vsensitivity:K\n" +
	"\bpii_type\x12\x1d.google.protobuf.FieldOptions\x18\xf1\xa2\x04 \x01(\x0e2\x0f.pii.v1.PiiTypeR\apiiType:M\n" +
	"\tpii_types\x12\x1d.google.protobuf.FieldOptions\x18\xf2\xa2\x04 \x03(\x0e2\x0f.pii.v1.PiiTypeR\bpiiTypes:i\n" +
	"\x12method_sensitivity\x12\x1e.google.protobuf.MethodOptions\x18\xf3\xa2\x04 \x01(\x0e2\x18.pii.v1.SensitivityLevelR\x11methodSensitivity:J\n" +
	"\x10audit_pii_access\x12\x1e.google.protobuf.MethodOptions\x18\xf4\xa2\x04 \x01(\bR\x0eauditPiiAccess:l\n" +
	"\x13message_sensitivity\x12\x1f.google.protobuf.MessageOptions\x18\xf5\xa2\x04 \x01(\x0e2\x18.pii.v1.SensitivityLevelR\x12messageSensitivityB\x95\x01\n" +
	"\n" +
	"com.pii.v1B\x10SensitivityProtoP\x01Z<github.com/bhatti/todo-api-errors/gen/api/proto/pii/v1;piiv1\xa2\x02\x03PXX\xaa\x02\x06Pii.V1\xca\x02\x06Pii\\V1\xe2\x02\x12Pii\\V1\\GPBMetadata\xea\x02\aPii::V1b\x06proto3"

var (
	file_api_proto_pii_v1_sensitivity_proto_rawDescOnce sync.Once
	file_api_proto_pii_v1_sensitivity_proto_rawDescData []byte
)

func file_api_proto_pii_v1_sensitivity_proto_rawDescGZIP() []byte {
	file_api_proto_pii_v1_sensitivity_proto_rawDescOnce.Do(func() {
		file_api_proto_pii_v1_sensitivity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_pii_v1_sensitivity_proto_rawDesc), len(file_api_proto_pii_v1_sensitivity_proto_rawDesc)))
	})
	return file_api_proto_pii_v1_sensitivity_proto_rawDescData
}

var file_api_proto_pii_v1_sensitivity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_pii_v1_sensitivity_proto_goTypes = []any{
	(SensitivityLevel)(0),               // 0: pii.v1.SensitivityLevel
	(PiiType)(0),                        // 1: pii.v1.PiiType
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
}
var file_api_proto_pii_v1_sensitivity_proto_depIdxs = []int32{
	2,  // 0: pii.v1.sensitivity:extendee -> google.protobuf.FieldOptions
	2,  // 1: pii.v1.pii_type:extendee -> google.protobuf.FieldOptions
	2,  // 2: pii.v1.pii_types:extendee -> google.protobuf.FieldOptions
	3,  // 3: pii.v1.method_sensitivity:extendee -> google.protobuf.MethodOptions
	3,  // 4: pii.v1.audit_pii_access:extendee -> google.protobuf.MethodOptions
	4,  // 5: pii.v1.message_sensitivity:extendee -> google.protobuf.MessageOptions
	0,  // 6: pii.v1.sensitivity:type_name -> pii.v1.SensitivityLevel
	1,  // 7: pii.v1.pii_type:type_name -> pii.v1.PiiType
	1,  // 8: pii.v1.pii_types:type_name -> pii.v1.PiiType
	0,  // 9: pii.v1.method_sensitivity:type_name -> pii.v1.SensitivityLevel
	0,  // 10: pii.v1.message_sensitivity:type_name -> pii.v1.SensitivityLevel
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	6,  // [6:11] is the sub-list for extension type_name
	0,  // [0:6] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_pii_v1_sensitivity_proto_init() }
func file_api_proto_pii_v1_sensitivity_proto_init() {
	if File_api_proto_pii_v1_sensitivity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_pii_v1_sensitivity_proto_rawDesc), len(file_api_proto_pii_v1_sensitivity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_pii_v1_sensitivity_proto_goTypes,
		DependencyIndexes: file_api_proto_pii_v1_sensitivity_proto_depIdxs,
		EnumInfos:         file_api_proto_pii_v1_sensitivity_proto_enumTypes,
		ExtensionInfos:    file_api_proto_pii_v1_sensitivity_proto_extTypes,
	}.Build()
	File_api_proto_pii_v1_sensitivity_proto = out.File
	file_api_proto_pii_v1_sensitivity_proto_goTypes = nil
	file_api_proto_pii_v1_sensitivity_proto_depIdxs = nil
}
